name       : python-clikit
version    : 0.6.2
release    : 1
source     :
    - https://pypi.io/packages/source/c/clikit/clikit-0.6.2.tar.gz : 442ee5db9a14120635c5990bcdbfe7c03ada5898291f0c802f77be71569ded59
license    : MIT
component  : programming.python
summary    : CliKit is a group of utilities to build beautiful and testable command line interfaces.
description: |
    CliKit is a group of utilities to build beautiful and testable command line interfaces.
rundeps    :
    - python-pastel
    - python-pylev
build      : |
    %python3_setup
install    : |
    %python3_install
